spring:
   profiles:
      active: dev
   jackson:
      date-format: "yyyy-MM-dd HH:mm:ss"
      time-zone: "GMT+8" 
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB
#   mvc: 
#      view: 
#         prefix: ""
#         suffix: ".html"
mybatis:
  mapper-locations: classpath:mapper/*.xml

