wechat: 
   appid: wxabd5e4915643494a
   secret: 4b83a8ba046e09281a670b85fa6de88a
   appid1: wx058b46db3cd0e979
   secret1: 7f4d1707caf9abaaf0b37aa03e6674f3
   appid2: wxdfa614160f40492d
   secret2: cee8748c023b1b97859a047e95ebf14c
gogirl:
   path:
      PICTURE: "classpath:/img/"
   url:
      NGINX: "http://192.168.1.2/gogirl/"
      GOGIRLMP: "http://192.168.1.2:8088/"
      GOGIRLUSER: "http://192.168.1.2:8089/"
      GOGIRLPAYMENT: "http://192.168.1.2:8087/"
      GOGIRLSTORE: "http://192.168.0.104:8081/"
      GOGIRLSERVICE: "http://192.168.0.104:8082/"
      GOGIRLTECHNICIAN: "http://192.168.0.104:8083/"
      GOGIRLORDER: "http://192.168.0.104:8084/"
      ERROR_PAGE: "http://192.168.1.2/redirect/error"
      picturePath: "E:\\gogirlPic\\picture\\grouppic\\"
server: 
   port: 8090
   servlet:
      context-path: /gogirl
   tomcat:
      max-threads: 10
      basedir: "E:\\gogirlPic\\picture\\"
spring:
   datasource:
      url: jdbc:mysql://cdb-554jnvol.gz.tencentcdb.com:10105/bailun_bendi?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: "#7kfnymAM$Y9-Ntf"
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime : 30000
      connection-test-query: "SELECT 1"
      hikari: 
         read-only: false
         connection-timeout: 60000
         idle-timeout: 60000
         validation-timeout: 3000
         max-lifetime: 60000
         login-timeout: 5
         maximum-pool-size: 60
         minimum-idle: 10
   http:
      multipart:
         location: "E:\\gogirlPic\\picture\\"